### PR TITLE
ARQGRA-483 ARQ-2014 Improved initial validation and URL resolution

### PR DESCRIPTION
**Pull request by MatousJobanek**

### CODE REVIEW

**Comment by MatousJobanek** [comment]
Related PR: https://github.com/arquillian/arquillian-graphene/pull/153

**Comment by MatousJobanek** [comment]
Tested locally - added graphene dependency (containing the fix mentioned above) and ran the whole test suite - passed.

**Comment by lfryc** [comment]
Nice!

Question is if we should make this a part of Warp's "extended" test suite.

**Comment by lfryc** [comment]
Landed :rocket:

**Pull request closed without merging**
