### PR TITLE
Upgrade maven-wrapper to 3.3.2.

### PR DESCRIPTION
**Pull request by rhusar**

### CODE REVIEW

**Comment by WolfgangHG** [comment]
@rhusar  How did you update the wrapper? As the file "maven-wrapper.jar" was deleted, I assume you used one of the "-Dtype" switches?

I did some updates to the wrapper in the past (#124 and #146), but I used the default config.

**Comment by rhusar** [comment]
> @rhusar How did you update the wrapper? As the file "maven-wrapper.jar" was deleted, I assume you used one of the "-Dtype" switches?
> 
> I did some updates to the wrapper in the past (#124 and #146), but I used the default config.

I just always use the default:

`mvn wrapper:wrapper -U`

Let me know if there's some problem, but this is even used by CI since this forces a maven version to use.

**Comment by WolfgangHG** [comment]
@rhusar Nope, no problem at all. I was just irritated that the jar file was deleted. But it seems that this is the default behavior when running "mvn wrapper:wrapper" - it uses "only-script":

```
[INFO] Unpacked only-script type wrapper distribution org.apache.maven.wrapper:maven-wrapper-distribution:zip:only-script:3.3.2
```

So I used some different argument when I updated it some time ago. But I did this only because the jar was present already, so I tried to do it the same way.

**Comment by rhusar** [comment]
> @rhusar Nope, no problem at all. I was just irritated that the jar file was deleted. But it seems that this is the default behavior when running "mvn wrapper:wrapper" - it uses "only-script":
> 
> ```
> [INFO] Unpacked only-script type wrapper distribution org.apache.maven.wrapper:maven-wrapper-distribution:zip:only-script:3.3.2
> ```
> 
> So I used some different argument when I updated it some time ago. But I did this only because the jar was present already, so I tried to do it the same way.

The removal of the jar file is actually intentional and this repo should eventually have a strict no binary files policy going forward. Unfortunately there are a few binary files in the repo atm

i/-text w/-text attr/                 	ftest/src/main/webapp/resources/empty.png
i/-text w/-text attr/                 	wiki/enrichment.dia
i/-text w/-text attr/                 	wiki/enrichment.png
i/-text w/-text attr/                 	wiki/server-round-trip.dia
i/-text w/-text attr/                 	wiki/server-round-trip.png

but those are safe.

**Pull request merged**
