### PR TITLE
TomEE profile: switch to TomEE 10 M3, wildfly-arquillian-container 5.0.1

### LINKED ISSUE #242: Restore TomEE support in test suite
@rhusar I struggled a bit with TomEE.

Version 9.1 supports only JakartaEE 9.1 (https://tomee.apache.org/comparison.html)
There is at least one test that fails (`org.jboss.arquillian.warp.jsf.ftest.redirection.TestJsfRedirect`), because the jsf pages fail on TomEE 9 with the current JakartaEE 10 namespaces and work only with the JakartaEE 9 namespaces (`xmlns:ui="http://xmlns.jcp.org/jsf/facelets"` instead of `xmlns:ui="jakarta.faces.facelets"`). And this would break WildFly and JakartaEE 10.

So we would have to switch to version 10.0, which is still in development (currently: M2) and supports JakartaEE 10. But it requires Java 17.

This is only a matter of the test suite, arquillian-extension-warp could probably be built with Java 11. But we would have to run the "tomee-managed" profile with Java 17. Would this be possible with Github CI and would this be OK for you?

In the moment I observe a HTMLUnit javascript parse error in `org.jboss.arquillian.warp.jsf.ftest.producer.TestJSFTestEnrichers` - might be caused by the fact that TomEE uses MyFaces, while WildFly used Mojarra. Will have to dig further...

### PR DESCRIPTION
**Pull request by WolfgangHG**
Partially resolves #242: TomEE 10 is JakartaEE10 compliant, but not final. More details in this issue.

Also updates the constant "version.wildfly.arquillian.container" to "5.0.1.Final" (don't know why dependabot did not pick it).

### CODE REVIEW

**Review by rhusar — CHANGES_REQUESTED** [review]
Starting to look good - but needs enabling CI changing these lines:

https://github.com/arquillian/arquillian-extension-warp/blob/main/.github/workflows/ci.yml#L30-L31

**Comment by WolfgangHG** [comment]
@rhusar About enabling the profile: see my comment in #242 - this is not possible due to the HtmlUnit error.

**Comment by rhusar** [comment]
FYI debugging the dependabot:

2024-10-16T12:48:46.3256130Z updater | 2024/10/16 12:48:46 INFO <job_902042634> Latest version is 5.0.1.Final
2024-10-16T12:48:46.3262664Z updater | 2024/10/16 12:48:46 INFO <job_902042634> Pull request already exists for org.wildfly.arquillian:wildfly-arquillian-container-remote with latest version 5.0.1.Final

it's because it originally opened
https://github.com/arquillian/arquillian-extension-warp/pull/141

which we had to ignore:
https://github.com/arquillian/arquillian-extension-warp/pull/208

So, it will work for future versions.

**Comment by rhusar** [comment]
> @rhusar About enabling the profile: see my comment in #242 - this is not possible due to the HtmlUnit error.

Uh... I see. We cannot merge this without the rest of the tests running. Just add a quick temporary solution to skip the test on tomee:

    @BeforeClass
    public static void beforeClass() throws IOException, InterruptedException {
        Assume.assumeFalse( here check for the tomee system property );
    }

**Comment by rhusar** [comment]
> Do you mean something like this (didn't know what to check for, so I guessed ;-))?
> 
> ```
>     @BeforeClass
>     public static void beforeClass() throws IOException, InterruptedException {
>        String tomEEHome = (String) System.getProperty("tomee.home");
>        
>        Assume.assumeTrue(tomEEHome == null || tomEEHome.length() == 0);
>     }
> ```

Something like that, whatever works.

> This would only make sense if you can start the TomEE tests with Java 17 and avoid Java 11 here.

That needs to be excluded completely in GitHub Actions:
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow#excluding-matrix-configurations

**Comment by WolfgangHG** [comment]
Something like this in "ci.yml"?

```
  ci:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        # Keep this list as: all supported LTS JDKs, the latest GA JDK, and the latest EA JDK (optional).
        java:
          - 11
          - 17
          - 21
          - 23
        container:
          - wildfly-managed
          # TODO GlassFish 5 is not compatible with JDK 9 and newer
          # - glassfish-managed
           - tomee-managed
        exclude:
           - os: ubuntu-latest
             java: 11
             container: tomee-managed
```

**Comment by rhusar** [comment]
> Something like this in "ci.yml"?
> 
> ```
>   ci:
>     runs-on: ${{ matrix.os }}
>     timeout-minutes: 30
>     strategy:
>       fail-fast: false
>       matrix:
>         os:
>           - ubuntu-latest
>         # Keep this list as: all supported LTS JDKs, the latest GA JDK, and the latest EA JDK (optional).
>         java:
>           - 11
>           - 17
>           - 21
>           - 23
>         container:
>           - wildfly-managed
>           # TODO GlassFish 5 is not compatible with JDK 9 and newer
>           # - glassfish-managed
>            - tomee-managed
>         exclude:
>            - os: ubuntu-latest
>              java: 11
>              container: tomee-managed
> ```

That looks correct to me!

**Comment by WolfgangHG** [comment]
Yes, ci is back again ;-). Done for today....

**Review by rhusar — APPROVED** [review]

**Comment by rhusar** [comment]
Thanks @WolfgangHG !

**Pull request merged**
