### PR TITLE
Logging for LittleProxy

### PR DESCRIPTION
**Pull request by WolfgangHG**
Adds logging for LittleProxy in the internal testing projects "ftest" and "extension\jsf-ftest". This is done through Log4j2, which catches the log messages from SLF4J. This is a followup to #116

The current loglevel for LittleProxy is INFO. As there are just a handful of log messages at first proxy initialization start and at server shutdown, I think this does not clutter the console.

I used "log4j2.xml" instead of a ".properties" file, because I am a xml guy ;-). That's also the reason why I declared a schema location for the raw file of https://github.com/apache/logging-log4j2/blob/2.x/log4j-core/src/main/resources/Log4j-config.xsd - this brings code completion and validation in Eclipse.
If JBoss prefers the properties file, I can change this.

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
Thanks for all the great work @WolfgangHG 

@chengfang What do you think about getting some CI in place moving forward? That would help validate PRs automatically. It seems this repo was using Travis in good old times but this is all gone now. Shouldn't be hard to adjust CircleCI jobs for example and put it here.

**Comment by WolfgangHG** [comment]
@chengfang a little reminder about this pull request ;-).

**Review by chengfang — APPROVED** [review]

**Comment by chengfang** [comment]
@WolfgangHG your changes look good. Let's wait a bit for #101 and see if it works, or else we'll need to set up circle ci for our overdue ci testing.

**Comment by chengfang** [comment]
@WolfgangHG thanks!

**Pull request merged**
