### PR TITLE
Fixed ServletException serialVersionUID error for TomEE profile

### PR DESCRIPTION
**Pull request by WolfgangHG**
While researching something completely different, I finally found a resolution for the TomEE error in [#108](https://github.com/arquillian/arquillian-extension-warp/pull/108#issuecomment-1475388798) (TomEE servlet api implementation declares a different serialVersionUID for "ServletException" than the JBoss implementation does, and one test fails because of this conflict).

The fix sounds quite reasonable to me: instead of declaring a global dependency on "org.jboss.spec.javax.servlet:jboss-servlet-api_3.0_spec" in the two testing projects "ftest/pom.xml" and "jsf-ftest/pom.xml", I declare a dependency on the servlet api jar for each profile in "ftest-base/pom.xml", matching the server implementation. It is not perfect for WildFly, as WildFly 26 actually provides "org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:2.0.0.Final".

Somehow, even Eclipse allows to use e.g. "javax.servlet.ServletException" in test classes of the "jsf-ftest" project, though this is not used in the current code. I hope it is pulled from the default profile. This is the only place where I feel a bit unsecure about this change.

With this change, the profiles "wildfly-managed", "tomee-managed" and "glassfish-managed-4-0" all work without further modifcations. Would it be possible to add all three to "build.yml"?

### CODE REVIEW

**Comment by WolfgangHG** [comment]
Hmmm, I am not sure about this idea. I have a bad feeling about Eclipse maybe missing the dependency. Keep this pull request on hold for some time. I still think about it ;-)

**Comment by WolfgangHG** [comment]
OK, Eclipse seems to add all dependencies from the profile marked as "activeByDefault", so my solution seems to be valid.
Here is a screenshot of the "Maven Dependencies" with different active profiles:
servlet_api

**Comment by chengfang** [comment]
Although this allows us to test all containers, there are quite some duplicates. TBH, I like the existing solution better (i.e., to document what needs to be modified for tomee).

In the future when moving to support jakarta ee 10, all containers will be using the same servlet-api.jar, which I think is the best solution. If we were to add changes in this PR, they will need to be undo in the future.

So I guess I'm neutral. @WolfgangHG do you feel the immediate benefits worth the extra maintenance work mentioned above?

**Comment by chengfang** [comment]
@WolfgangHG just fyi, you may have noticed, I've just merged the upgrade to arquillian-core 1.7.0.Final in #129 . You may want to rebase and work with the what's latest in master.

**Comment by WolfgangHG** [comment]
OK. 
In order to avoid the same problems that I run into last time, I ask before failing ;-): is this guide the correct approach to rebase the branch in my fork? [https://johnnycase.github.io/post/2021/07/28/git-rebase-fork.html](https://johnnycase.github.io/post/2021/07/28/git-rebase-fork.html)

**Comment by chengfang** [comment]
@WolfgangHG that looks good guide.

This is what I have:
```
git remote -v

origin	https://github.com/chengfang/arquillian-extension-warp.git (fetch)
origin	https://github.com/chengfang/arquillian-extension-warp.git (push)
upstream	https://github.com/arquillian/arquillian-extension-warp.git (fetch)
upstream	https://github.com/arquillian/arquillian-extension-warp.git (push)
```

While inside a local topic branch with some local commits already done, I usually just pull from upstream/master to get all the latest into my local branch:
```
git pull --rebase upstream master
```

I configured .gitconfig to always pull with rebase, so as to do away with --rebase option. And also configured a git alias to make this common command shorter to run.

**Comment by WolfgangHG** [comment]
GlassFish profiles now use the JBoss API. And the tests ran again without errors.

You confused me a bit by editing my comment ;-)

**Comment by chengfang** [comment]
@WolfgangHG sorry, I meant to quote and reply, but somehow mixed up.

**Review by chengfang — APPROVED** [review]

**Comment by chengfang** [comment]
@WolfgangHG thanks!

**Comment by WolfgangHG** [comment]
@chengfang Your suggestion sounds good. Could you take care of this? I don't have knowledge of the automated builds.

**Comment by chengfang** [comment]
Sure, I'll work on enhancing the github actions CI jobs.

**Pull request merged**
